### ISSUE TITLE
sizeof is a keyword in C, but there are no expected behaviors in golden_scanner

### ISSUE THREAD

**Issue by William-Mou** [fffchameleon/compiler_testcase#4]
According to the following test data, `gold_scanner` may not process `sizeof` correctly.
I have asked the teaching assistant on [eeclass](https://eeclass.nthu.edu.tw/course/courseDiscuss/99819).

- [test/pragma](https://github.com/fffchameleon/compiler_testcase/blob/8d8d723ebda7b9fa48ca340e62e68161728a64ad/testcase/pragma#L6)
- [test/comment_test](https://github.com/fffchameleon/compiler_testcase/blob/8d8d723ebda7b9fa48ca340e62e68161728a64ad/testcase/comment_test#L12)

**Comment by William-Mou** [comment]
The specifications presented in the slides should guide our actions...

>同學好，
我們的spec要求實作Subset of C Language，因此需要按照投影片中列出的keywords列表來實作。
謝謝

**Comment by fffchameleon** [comment]
@William-Mou thanks for your information~
