### ISSUE TITLE
[Resourece] A dragon book exercise solution project

### ISSUE THREAD

**Issue by William-Mou** [fffchameleon/compiler_testcase#6]
https://github.com/alirezasamar/Dragon-Book-Solutions

**Comment by William-Mou** [comment]
Great tool for demonstrating the process of translating Regular Expressions to minimal DFAs.
For Ch3, Ch4
https://cyberzhg.github.io/toolbox/

**Comment by fffchameleon** [comment]
I have already added them to [README.md](https://github.com/fffchameleon/compiler_testcase/blob/main/README.md)
thanks for your offer
