### ISSUE TITLE
[Resource] Class slides from read-only Google Drive

### ISSUE THREAD

**Issue by William-Mou** [fffchameleon/compiler_testcase#7]
https://drive.google.com/drive/folders/17dhKeYC_U3vDPdbM88nAz2J3b5bC1M4l?usp=share_link

**Comment by William-Mou** [comment]
Great tool for demonstrating the process of translating Regular Expressions to minimal DFAs.
https://cyberzhg.github.io/toolbox/

**Comment by fffchameleon** [comment]
I have already added it to [README.md](https://github.com/fffchameleon/compiler_testcase/blob/main/README.md)
thanks for your offer
